// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddnewemployeefeatureTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addnewemployeefeature() {
    // Test name: Add new employee feature
    // Step # | name | target | value | comment

    //TC-1

    // 1 | open | /app/ |  | 
    driver.get("https://testco64.humanity.com/app/");
    // 2 | setWindowSize | 945x1020 |  | 
    driver.manage().window().setSize(new Dimension(945, 1020));
    // 3 | click | id=email |  | 
    driver.findElement(By.id("email")).click();
    // 4 | type | id=email | todo82@hotmail.com | 
    driver.findElement(By.id("email")).sendKeys("todo82@hotmail.com");
    // 5 | type | id=password | humanitytest | 
    driver.findElement(By.id("password")).sendKeys("humanitytest");
    // 6 | click | name=login |  | 
    driver.findElement(By.name("login")).click();
    // 7 | click | css=.primNavQtip__inner > .icon-user |  | 
    driver.findElement(By.cssSelector(".primNavQtip__inner > .icon-user")).click();
    // 8 | click | id=act_primary |  | 
    driver.findElement(By.id("act_primary")).click();
    // 9 | click | id=_asf1 |  | 
    driver.findElement(By.id("_asf1")).click();

    //TC-2

    // 10 | type | id=_asf1 | Michael | 
    driver.findElement(By.id("_asf1")).sendKeys("Michael");
    // 11 | click | id=_as_save_multiple |  | 
    driver.findElement(By.id("_as_save_multiple")).click();
    // 12 | click | id=act_primary |  |

    //TC-3

    driver.findElement(By.id("act_primary")).click();
    // 13 | click | id=_asf1 |  | 
    driver.findElement(By.id("_asf1")).click();
    // 14 | click | id=_asl1 |  | 
    driver.findElement(By.id("_asl1")).click();
    // 15 | type | id=_asl1 | Mayers | 
    driver.findElement(By.id("_asl1")).sendKeys("Mayers");
    // 16 | click | id=_as_save_multiple |  | 
    driver.findElement(By.id("_as_save_multiple")).click();
    // 17 | click | id=_asf1 |  |

    //TC-4

    driver.findElement(By.id("_asf1")).click();
    // 18 | type | id=_asf1 | David | 
    driver.findElement(By.id("_asf1")).sendKeys("David");
    // 19 | click | id=_as_save_multiple |  | 
    driver.findElement(By.id("_as_save_multiple")).click();
    // 20 | click | id=act_primary |  |

    //TC-5

    driver.findElement(By.id("act_primary")).click();
    // 21 | click | id=_asf1 |  | 
    driver.findElement(By.id("_asf1")).click();
    // 22 | type | id=_asf1 | Scott | 
    driver.findElement(By.id("_asf1")).sendKeys("Scott");
    // 23 | type | id=_asl1 | Abott | 
    driver.findElement(By.id("_asl1")).sendKeys("Abott");
    // 24 | click | id=_ase1 |  | 
    driver.findElement(By.id("_ase1")).click();
    // 25 | type | id=_ase1 | sa66@gmail.com | 
    driver.findElement(By.id("_ase1")).sendKeys("sa66@gmail.com");
    // 26 | click | id=_as_save_multiple |  | 
    driver.findElement(By.id("_as_save_multiple")).click();

    //TC-6

    // 27 | click | css=.staff-submenu-link:nth-child(1) |  | 
    driver.findElement(By.cssSelector(".staff-submenu-link:nth-child(1)")).click();
  }
}
