// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogintestHumanitydeshboardTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logintestHumanitydeshboard() {
    // TEST SUITE: LOGIN FORM
    // Test name: Login test Humanity deshboard
    // Step # | name | target | value | comment
    // 1 | open | /app/ |  |

    //TC-1

    driver.get("https://testco64.humanity.com/app/");
    // 2 | setWindowSize | 945x1020 |  | 
    driver.manage().window().setSize(new Dimension(945, 1020));
    // 3 | click | name=login |  | 
    driver.findElement(By.name("login")).click();
    // 4 | click | id=email |  |

    //TC-2

    driver.findElement(By.id("email")).click();
    // 5 | type | id=email | todo82@hotmail.com | 
    driver.findElement(By.id("email")).sendKeys("todo82@hotmail.com");
    // 6 | click | name=login |  | 
    driver.findElement(By.name("login")).click();

    //TC-3

    // 7 | click | id=password |  | 
    driver.findElement(By.id("password")).click();
    // 8 | type | id=password | humanitytest | 
    driver.findElement(By.id("password")).sendKeys("humanitytest");
    // 9 | click | name=login |  | 
    driver.findElement(By.name("login")).click();

    //TC-4

    // 10 | click | id=email |  | 
    driver.findElement(By.id("email")).click();
    // 11 | type | id=email | todo82@hotmail.com | 
    driver.findElement(By.id("email")).sendKeys("todo82@hotmail.com");
    // 12 | click | id=password |  | 
    driver.findElement(By.id("password")).click();
    // 13 | type | id=password | 111 | 
    driver.findElement(By.id("password")).sendKeys("111");
    // 14 | click | name=login |  | 
    driver.findElement(By.name("login")).click();

    //TC-5

    // 15 | click | id=email |  | 
    driver.findElement(By.id("email")).click();
    // 16 | type | id=email | todo82@hotmail.com | 
    driver.findElement(By.id("email")).sendKeys("todo82@hotmail.com");
    // 17 | click | id=password |  | 
    driver.findElement(By.id("password")).click();
    // 18 | type | id=password | humanitytest | 
    driver.findElement(By.id("password")).sendKeys("humanitytest");
    // 19 | click | name=login |  | 
    driver.findElement(By.name("login")).click();
  }
}
